name: Build and Deploy Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: image-name
        registry: ghcr.io
        githubOrg: kinoide
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
